version: '2'
services:
  elasticsearch:
    image: elasticsearch:c5.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=kibana-cluster-test
      - ELASTICSEARCH_TAG_ESGROUP=kibana_clone_454
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
      - ELASTICSEARCH_ENV_LOCAL=true
  kibana:
    image: kibana:5.2.0
    ports:
      - "5601:5601"
    container_name: kibana
    environment:
      - ELSTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
  cerebro:
    image: snuids/cerebro:latest
    container_name: cerebro
    ports:
      - "9000:9000"
    links:
      - elasticsearch
