version: '2'
services:
  elasticsearch:
    build: ./elasticsearch/2.4.4
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=kibana-cluster
      - ELASTICSEARCH_TAG_ESGROUP=kibana
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
      - ELASTICSEARCH_ENV_LOCAL=true
  kibana:
    build: ./kibana/4.6.4
    ports:
      - "5601:5601"
    container_name: kibana
    environment:
      - ELSTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
