version: '2'
services:
  elasticsearch:
    image: elasticsearch:c2.4.4
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=kibana-cluster-test
      - ELASTICSEARCH_TAG_ESGROUP=kibana_clone_454
      - ES_HEAP_SIZE=2g
      - ES_HEAP_NEWSIZE=1g
      - ELASTICSEARCH_ENV_LOCAL=true
  kibana:
    image: kibana:c4.6.4
    ports:
      - "5601:5601"
    container_name: kibana
    environment:
      - ELSTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
