version: '2'

services:
  gitlab-ci-multi-runner:
    image: sameersbn/gitlab-ci-multi-runner:1.1.4-7
    container_name: gitlab_runner
    restart: always
    volumes:
      - $PWD/gitlab-runner:/home/gitlab_ci_multi_runner/data
    environment:
      - CI_SERVER_URL=http://gitlab/ci
      - RUNNER_TOKEN=your_token
      - RUNNER_DESCRIPTION=myrunner
      - RUNNER_EXECUTOR=shell
